# GitLeaks 설정 파일
# 시크릿 스캔을 위한 규칙 정의

title = "EAI Schema Toolkit GitLeaks 설정"

# 스캔할 파일 확장자
[extend]
useDefault = true

# 커스텀 규칙
[[rules]]
id = "heroku-api-key"
description = "Heroku API Key"
regex = '''[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'''
tags = ["key", "heroku"]

[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''eyJ[A-Za-z0-9_-]*\.eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*'''
tags = ["jwt", "token"]

[[rules]]
id = "mongodb-connection"
description = "MongoDB Connection String"
regex = '''mongodb(\+srv)?://[^\s]+'''
tags = ["database", "mongodb"]

[[rules]]
id = "redis-url"
description = "Redis URL"
regex = '''redis://[^\s]+'''
tags = ["database", "redis"]

# 허용 목록 (false positive 방지)
[allowlist]
description = "허용된 파일 및 패턴"
files = [
    ".gitleaks.toml",
    "package-lock.json",
    ".github/workflows/*.yml"
]

paths = [
    '''node_modules/''',
    '''dist/''',
    '''coverage/''',
    '''.git/'''
]

regexes = [
    '''example\.com''',
    '''localhost''',
    '''127\.0\.0\.1''',
    '''test-.*''',
    '''mock-.*''',
    '''fake-.*''',
    '''dummy-.*'''
]