<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://example.com/test"
             targetNamespace="http://example.com/test">
  <types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://example.com/test">
      <element name="TestElement" type="string"/>
    </schema>
  </types>
  <message name="TestMessage">
    <part name="parameter" element="tns:TestElement"/>
  </message>
  <portType name="TestPortType">
    <operation name="TestOperation">
      <input message="tns:TestMessage"/>
    </operation>
  </portType>
</definitions>